### ISSUE TITLE
Phase2.csv is empty

### ISSUE THREAD

**Issue by aggarwalnisha** [jprellberg/isbi2019cancer#4]
The phase2.csv, i.e C-NMC_test_prelims_phase_data_labels.csv is empty when I downloaded it. Can you help me in this regard? Thanks

**Comment by jprellberg** [comment]
Data is not included in this repository for legal reasons. You have to obtain it from the challenge. I can only point you to the data upload by the challenge organizers:
https://wiki.cancerimagingarchive.net/display/Public/C_NMC_2019+Dataset%3A+ALL+Challenge+dataset+of+ISBI+2019

It might be that the files there are organized differently in that archive since it was released in phases during the challenge.
